### ISSUE TITLE
About page expired thing.

### ISSUE THREAD

**Issue by Lupen-bit** [CLOEI/Mate#1]
Hello Cloe, first of all, what you are doing is very cool and it makes me happy to see you working in a current way. I would like to mention some minor mistakes. We need to send the Hello packet to the dashboard exactly as in the original packages. When sending it, we need to use a method called URL encoding and apply it to the body. For example, it should proceed as follows: requestedname%7C%20%26%20..%2F. Additionally, the way you are requesting it is progressing incorrectly, incomplete, and insufficient

you can contact me on discord : 
growtopianews

**Comment by CLOEI** [comment]
Hello @Lupen-bit, I understand what you're saying, first of all thank you for pointing it out. I haven't reach to the point where I handle the tank packet yet, so I couldn't verify if my implementation is correct. However, the current implementation produces the same output as my pre-encoded version. I tested this on commit [c2fd0a7](https://github.com/CLOEI/Mate/commit/c2fd0a717cf9637370d500ae9c8268ba3b022e53) where I replaced the old implementation with the current one.

I haven't encountered the URL point expiration issue yet. I'm currently developing on a Windows machine during weekends. I'll check if it occurs on other platforms (like Linux) tomorrow.

My assumption was that the request body would be automatically encoded, hence the current implementation. If this is incorrect, I'll replace it and add a utility to encode the URL. Please share your thoughts on this.

Thank you for your kind comment. It really made my day! I'll continue working on the project.

**Comment by Lupen-bit** [comment]
Firstly, thank you for your response and for answering so kindly. I intended to open an issue regarding the C++ repository “Mori” that you wrote, but I see that I mistakenly opened it under “Mate” due to a small typing error. Please overlook this embarrassing mistake 😂 

I like your writing and method selection style, and I offer you the opportunity to continue this project together. I have already provided my Discord address, and I would be happy if you could reach out to me.

**Comment by CLOEI** [comment]
Haha, don't worry! After what you said earlier, I'm considering switching from the current legacy headless browser method to a faster, more efficient approach using a POST request. I originally chose headless browser because I couldn't get POST requests to work in the C++ repo. I'll try encoding the payload beforehand. I'll be contacting you on discord!

**Comment by CLOEI** [comment]
I updated the legacy method on this commit [#9544101](https://github.com/CLOEI/Mate/commit/9544101d8415a01315adc5853432bfdf214311d9)
